### ISSUE TITLE
kubectl doesn't work with the default vagrant install

### ISSUE THREAD

**Issue by smesch** [mantl/mantl#1802]
.kube/config:

``` yaml
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://192.168.100.101/kubeapi
  name: mantl
contexts:
- context:
    cluster: mantl
    user: mantl-basic-auth
  name: mantl
current-context: mantl
kind: Config
preferences: {}
users:
- name: mantl-basic-auth
  user:
    password: password
    username: admin
```

```
$ kubectl get nodes
The connection to the server 192.168.100.101 was refused - did you specify the right host or port?
```

If I change server to `server: https://192.168.100.101:6443`, kubectl starts working.
- Ansible version (`ansible --version`): 2.1.0.0
- Python version (`python --version`): 2.7.10
- Git commit hash or branch: master
- Cloud Environment: local (vagrant)
- Terraform version (`terraform version`): n/a
