### ISSUE TITLE
mantl-api and mesos-consul docker keep restarting when deploying mantl

### ISSUE THREAD

**Issue by zhangqx2010** [mantl/mantl#1866]
I followed Bare-Metal installation on RHEL 7.2 using mantl-1.2.0
mantl UI can't be accessed after ansible run.
After run ansible playbook by command
```
ansible-playbook -i hosts-inventory -e provider=bare-metal         -e consul_dc=dc1         -e docker_lvm_backed=true         -e docker_lvm_data_volume_size="80%FREE"         -e @security.yml  sample.yml >& bare-metal.log
```
I can see tasks successful in logs
```
PLAY RECAP ******************************************************************** 
common | install system utilities -------------------------------------- 20.48s
zookeeper | install zookeeper package ---------------------------------- 18.87s
marathon | restart marathon -------------------------------------------- 11.36s
common | enable EPEL repo ---------------------------------------------- 11.12s
mesos | wait for zookeeper service to be registered -------------------- 10.33s
marathon | wait for zookeeper service to be registered ----------------- 10.25s
lvm | install LVM tools ------------------------------------------------- 7.54s
docker | install docker-gc ---------------------------------------------- 7.43s
common | install fail2ban ----------------------------------------------- 7.17s
lvm | install latest device-mapper-libs --------------------------------- 6.97s
1VM             : ok=216  changed=60   unreachable=0    failed=0   
2VM               : ok=216  changed=60   unreachable=0    failed=0   
3VM               : ok=216  changed=60   unreachable=0    failed=0   
4VM               : ok=138  changed=24   unreachable=0    failed=0   
5VM               : ok=138  changed=24   unreachable=0    failed=0   
6VM               : ok=138  changed=24   unreachable=0    failed=0   
7VM               : ok=120  changed=20   unreachable=0    failed=0   
8VM               : ok=120  changed=20   unreachable=0    failed=0   
localhost                  : ok=0    changed=0    unreachable=0    failed=0 
```
While I see error logs from mesos
mesos-consul  err:
```
I0217 06:50:04.809731 17099 exec.cpp:143] Version: 0.28.2
I0217 06:50:04.813161 17103 exec.cpp:217] Executor registered on slave 91f3a914-4f52-49c4-8ed1-0ee073ea02e5-S0
2017/02/17 06:50:05 Failed to connect to x.x.x.41:2181: dial tcp x.x.x.41:2181: i/o timeout
2017/02/17 06:50:06 Failed to connect to x.x.x.42:2181: dial tcp x.x.x.42:2181: i/o timeout
2017/02/17 06:50:07 Failed to connect to x.x.x.43:2181: dial tcp x.x.x.43:2181: i/o timeout
2017/02/17 06:50:10 Failed to connect to x.x.x.41:2181: dial tcp x.x.x.41:2181: i/o timeout
2017/02/17 06:50:11 Failed to connect to x.x.x.42:2181: dial tcp x.x.x.42:2181: i/o timeout
2017/02/17 06:50:12 Failed to connect to x.x.x.43:2181: dial tcp x.x.x.43:2181: i/o timeout
2017/02/17 06:50:14 Failed to connect to x.x.x.41:2181: dial tcp x.x.x.41:2181: i/o timeout
2017/02/17 06:50:15 Failed to connect to x.x.x.42:2181: dial tcp x.x.x.42:2181: i/o timeout
2017/02/17 06:50:16 Failed to connect to x.x.x.43:2181: dial tcp x.x.x.43:2181: i/o timeout
2017/02/17 06:50:18 Failed to connect to x.x.x.41:2181: dial tcp x.x.x.41:2181: i/o timeout
2017/02/17 06:50:19 Failed to connect to x.x.x.42:2181: dial tcp x.x.x.42:2181: i/o timeout
2017/02/17 06:50:20 Failed to connect to x.x.x.43:2181: dial tcp x.x.x.43:2181: i/o timeout
2017/02/17 06:50:22 Failed to connect to x.x.x.41:2181: dial tcp x.x.x.41:2181: i/o timeout
2017/02/17 06:50:23 Failed to connect to x.x.x.42:2181: dial tcp x.x.x.42:2181: i/o timeout
repeated many times
time="2017-02-17T06:52:04Z" level=fatal msg="Timed out waiting for initial ZK detection." 
```
mantl-api error:
```
I0217 07:15:20.636468 23389 exec.cpp:143] Version: 0.28.2
I0217 07:15:20.640496 23394 exec.cpp:217] Executor registered on slave 91f3a914-4f52-49c4-8ed1-0ee073ea02e5-S0
time="2017-02-17T07:15:20Z" level=info msg="Starting mantl-api v0.2.0" 
time="2017-02-17T07:15:20Z" level=debug msg="Using Consul at consul.service.consul:8500 over https" 
time="2017-02-17T07:15:50Z" level=fatal msg="Could not connect to consul: Get https://consul.service.consul:8500/v1/kv/mantl-install: dial tcp x.x.x.42:8500: i/o timeout" 
W0217 07:15:20.640496 23398 logging.cpp:88] RAW: Received signal SIGTERM from process 24764 of user 0; exiting
```

Nothing come out when try on x.x.x.46:
```
curl -k http:// consul.service.consul:8500/v1/kv/mantl-install
```

I think key-value is missing in consul for mantl-api docker init.
Do I miss something during installation?

- Logs from the failing component, if applicable. Might be any of the following:
    - `journalctl --no-pager -l -u <component>`
    - `docker logs <container>`
    - `kubectl logs <pod>`
    - Sandbox logs from the Mesos UI

docker logs and sandbox logs is attached above

- Changes made to `sample.yml`, if applicable.
I comment out kuber related parts
```
---
# CHECK SECURITY - when customizing you should leave this in. If you
# take it out and forget to specify security.yml, security could be turned off
# on components in your cluster!
- include: "{{ playbook_dir }}/playbooks/check-requirements.yml"

# BASICS - we need every node in the cluster to have common software running to
# increase stability and enable service discovery. You can look at the
# documentation for each of these components in their README file in the
# `roles/` directory, or by checking the online documentation at
# docs.mantl.io.
- hosts: all
  vars:
    # consul_acl_datacenter should be set to the datacenter you want to control
    # Consul ACLs. If you only have one datacenter, set it to that or remove
    # this variable.
    # consul_acl_datacenter: your_primary_datacenter

    consul_servers_group: role=control
  roles:
    - common
    - lvm
    - docker
    - logrotate
    - consul-template
    - nginx
    - consul
    - etcd
    - dnsmasq

# ROLES - after provisioning the software that's common to all hosts, we do
# specialized hosts. This configuration has two major groups: control nodes and
# worker nodes. We provision the worker nodes first so that we don't create any
# race conditions. This could happen in the Mesos components - if there are no
# worker nodes when trying to schedule control software, the deployment process
# would hang.
#
# The worker role itself has a minimal configuration, as it's designed mainly to
# run software that the Mesos leader shedules. It also forwards traffic to
# globally known ports configured through Marathon.
- hosts: role=worker
  # role=worker hosts are a subset of "all". Since we already gathered facts on
  # all servers, we can skip it here to speed up the deployment.
  gather_facts: no
  vars:
    mesos_mode: follower
    zookeeper_server_group: role=control
  roles:
    - mesos
    - calico

#- hosts: role=kubeworker
#  gather_facts: yes
#  roles:
#    - calico
#    - kubernetes
#    - kubernetes-node

# the control nodes are necessarily more complex than the worker nodes, and have
# ZooKeeper, Mesos, and Marathon leaders. In addition, they control Vault to
# manage secrets in the cluster. These servers do not run applications by
# themselves, they only schedule work. That said, there should be at least 3 of
# them (and always an odd number) so that ZooKeeper can get and keep a quorum.
- hosts: role=control
  gather_facts: yes
  vars:
    consul_servers_group: role=control
    mesos_leaders_group: role=control
    mesos_mode: leader
    zookeeper_server_group: role=control
  roles:
    - vault
    - zookeeper
    - mesos
    - calico
    - marathon
    - mantlui
#    - kubernetes
#    - kubernetes-master
#    - kubernetes-addons

# The edge role exists solely for routing traffic into the cluster. Firewall
# settings should be such that web traffic (ports 80 and 443) is exposed to the
# world.
- hosts: role=edge
  gather_facts: yes
  vars:
    # this is the domain that traefik will match on to do host-based HTTP
    # routing. Set it to a domain you control and add a star domain to route
    # traffic. (EG *.marathon.localhost)
    #
    # For those migrating from haproxy, this variable serves the same purpose
    # and format as `haproxy_domain`.
    traefik_marathon_domain: marathon.localhost
  roles:
    - traefik
```

inventory
```
[role=control]
1VM private_ipv4=x.x.x.41 ansible_ssh_host=x.x.x.41
2VM private_ipv4=x.x.x.42 ansible_ssh_host=x.x.x.42
3VM private_ipv4=x.x.x.43 ansible_ssh_host=x.x.x.43

[role=control:vars]
consul_is_server=true
lvm_physical_device=/dev/sdc1

[role=worker]
4VM private_ipv4=x.x.x.44 ansible_ssh_host=x.x.x.44
5VM private_ipv4=x.x.x.45 ansible_ssh_host=x.x.x.45
6VM private_ipv4=x.x.x.46 ansible_ssh_host=x.x.x.46

[role=worker:vars]
consul_is_server=false
lvm_physical_device=/dev/sdc1

[role=edge]
7VM private_ipv4=x.x.x.47 ansible_ssh_host=x.x.x.47
8VM private_ipv4=x.x.x.48 ansible_ssh_host=x.x.x.48

[role=edge:vars]
consul_is_server=false
lvm_physical_device=/dev/sdc1

[dc=dc1]
1VM
2VM
3VM
4VM
5VM
6VM
7VM
8VM
```

- Ansible version (`ansible --version`):
```
ansible --version
ansible 1.9.6
```
- Python version (`python --version`):
```
python --version
Python 2.7.5
```
- Git commit hash or branch:
- Cloud Environment:
- Terraform version (`terraform version`):
