### ISSUE TITLE
python-pip errors

### ISSUE THREAD

**Issue by thomasvincent** [mantl/mantl#1922]
python-pip errors reported in health checks. Hypothetical fix is to make sure dependencies python2-pip , python-pip are installed on all nodes. 

Reported by @berle

**Comment by Theaxiom** [comment]
I did that here and it had no effect: https://github.com/mantl/mantl/commit/cee79f2f2325f4aebcc85ed305b2b711fe9e5169

**Comment by Theaxiom** [comment]
Oh I think I got the fix, give me a few.

**Comment by Theaxiom** [comment]
Looks like `common` packages are not being installed on all nodes, kinda defeats the purpose. Fixing it now.

**Comment by Cryptophobia** [comment]
@Theaxiom yep, nice find! common playbook is missing from the sample.yml playbook on the `worker`, `kuberworker`, and `edge` nodes.

**Comment by Theaxiom** [comment]
Yeah, the common `role`, not `playbook`. ;)

**Comment by Cryptophobia** [comment]
@Theaxiom a role is basically a playbook :P

**Comment by Theaxiom** [comment]
A role is a collection of tasks, templates, vars, defaults, etc; a playbook is a collection of roles, vars and targeting rules. ;)

Playbook > Role > Task

**Comment by Cryptophobia** [comment]
@Theaxiom The main difference is that a playbook can contain a role. 💃

**Comment by Theaxiom** [comment]
Ok, it looks like `python2-pip` is installed which supersedes `python-pip`, something is checking for `python-pip` and not acknowledging `python2-pip`.

**Comment by Theaxiom** [comment]
This solves the problem:
```
- hosts: all
  gather_facts: no
  tasks:
  - name: update json healthchecks
    replace: dest=/etc/distributive.d/distributive-common.json regexp='python-pip' replace='python2-pip'
```
